# Generated by Django 4.2.24 on 2025-10-22 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cost.category",
            ),
        ),
    ]
