# Generated by Django 4.2.24 on 2025-10-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0002_cost_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        max_length=50,
                    ),
                ),
                ("frequency_number", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="cost",
            name="frequency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cost.frequency",
            ),
        ),
    ]
