# Generated by Django 6.0.5 on 2026-07-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0003_costchange"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costchange",
            options={},
        ),
        migrations.RenameField(
            model_name="costchange",
            old_name="prevous_amount",
            new_name="previous_amount",
        ),
        migrations.AlterField(
            model_name="costchange",
            name="cost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_changes",
                to="cost.cost",
            ),
        ),
        migrations.AddConstraint(
            model_name="costchange",
            constraint=models.UniqueConstraint(
                models.F("date_changed"),
                models.F("cost"),
                name="unique_cost_change_per_day",
            ),
        ),
    ]
