# Generated by Django 4.2.24 on 2025-10-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0003_frequency_alter_cost_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cost",
            name="frequency",
        ),
        migrations.AddField(
            model_name="cost",
            name="frequency_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cost",
            name="frequency_unit",
            field=models.CharField(
                choices=[
                    ("days", "Days"),
                    ("weeks", "Weeks"),
                    ("months", "Months"),
                    ("years", "Years"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Frequency",
        ),
    ]
