# Generated by Django 4.2.25 on 2025-10-25 10:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0004_remove_cost_frequency_cost_frequency_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="anchor_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
