# Generated by Django 4.2.24 on 2025-10-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0005_cost_anchor_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cost",
            options={"ordering": ["-amount"]},
        ),
    ]
