# Generated by Django 5.2.12 on 2026-04-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0006_alter_cost_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cost",
            name="anchor_date",
        ),
        migrations.AddField(
            model_name="cost",
            name="last_paid_date",
            field=models.DateField(null=True),
        ),
    ]
