# Generated by Django 5.2.13 on 2026-05-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0007_remove_cost_anchor_date_cost_last_paid_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="last_paid_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
