# Generated by Django 5.2.13 on 2026-05-02 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category"),
        ("cost", "0008_alter_cost_last_paid_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
