# Generated by Django 5.2.13 on 2026-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0009_alter_cost_category_delete_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cost",
            old_name="frequency_number",
            new_name="frequency_value",
        ),
        migrations.AlterField(
            model_name="cost",
            name="frequency_unit",
            field=models.CharField(
                choices=[
                    ("day", "Day(s)"),
                    ("week", "Week(s)"),
                    ("month", "Month(s)"),
                    ("year", "Year(s)"),
                ],
                max_length=50,
            ),
        ),
    ]
