# Generated by Django 5.2.13 on 2026-05-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0010_rename_frequency_number_cost_frequency_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="frequency_unit",
            field=models.CharField(
                choices=[
                    ("days", "Day(s)"),
                    ("weeks", "Week(s)"),
                    ("months", "Month(s)"),
                    ("years", "Year(s)"),
                ],
                default="months",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cost",
            name="frequency_value",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
