# Generated by Django 5.2.13 on 2026-05-03 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0011_alter_cost_frequency_unit_alter_cost_frequency_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cost",
            name="last_paid_date",
        ),
        migrations.AddField(
            model_name="cost",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
