# Generated by Django 5.2.13 on 2026-05-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0012_remove_cost_last_paid_date_cost_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="CostKeywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=50)),
                (
                    "cost",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="cost.cost",
                    ),
                ),
            ],
        ),
    ]
