# Generated by Django 5.2.13 on 2026-05-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cost", "0013_costkeywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="cost",
            name="keywords",
            field=models.CharField(
                blank=True, help_text="Comma-separated list", max_length=500
            ),
        ),
        migrations.DeleteModel(
            name="CostKeywords",
        ),
    ]
