# Generated by Django 6.0.5 on 2026-05-12 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_merge_20260512_0104"),
        ("cost", "0014_cost_keywords_delete_costkeywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cost",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
    ]
