# Generated by Django 5.2.13 on 2026-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="budget_interval_value",
            field=models.PositiveIntegerField(
                default=14,
                help_text="Days for 'Fixed Days', or the date (1-31) for 'Day of Month'.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="budget_type",
            field=models.CharField(
                choices=[("days", "Fixed number of Days"), ("monthly", "Day of Month")],
                default="days",
                max_length=10,
            ),
        ),
    ]
