# Generated by Django 6.0.5 on 2026-05-18 03:55

import uuid

from django.db import migrations, models


def gen_uuids(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.all():
        user.uid = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(gen_uuids),
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
