# Generated by Django 6.0.5 on 2026-05-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_user_uid"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
