# Generated by Django 6.0.5 on 2026-07-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(default="light", max_length=20),
        ),
    ]
