# Generated by Django 5.2.13 on 2026-05-02 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_category_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="budget_interval_value",
            new_name="budget_interval",
        ),
        migrations.AddField(
            model_name="user",
            name="start_pay_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="user",
            name="budget_type",
            field=models.CharField(
                choices=[
                    ("day", "Day(s)"),
                    ("week", "Week(s)"),
                    ("month", "Month(s)"),
                    ("year", "Year(s)"),
                ],
                default="day",
                max_length=10,
            ),
        ),
    ]
