# Generated by Django 6.0.5 on 2026-07-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userpreferences_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                choices=[
                    ("light", "Light"),
                    ("dark", "Dark"),
                    ("cupcake", "Cupcake"),
                    ("bumblebee", "Bumblebee"),
                    ("emerald", "Emerald"),
                    ("corporate", "Corporate"),
                    ("synthwave", "Synthwave"),
                    ("retro", "Retro"),
                    ("cyberpunk", "Cyberpunk"),
                    ("valentine", "Valentine"),
                    ("halloween", "Halloween"),
                    ("garden", "Garden"),
                    ("forest", "Forest"),
                    ("aqua", "Aqua"),
                    ("lofi", "Lofi"),
                    ("pastel", "Pastel"),
                    ("fantasy", "Fantasy"),
                    ("wireframe", "Wireframe"),
                    ("black", "Black"),
                    ("luxury", "Luxury"),
                    ("dracula", "Dracula"),
                    ("cmyk", "Cmyk"),
                    ("autumn", "Autumn"),
                    ("business", "Business"),
                    ("acid", "Acid"),
                    ("lemonade", "Lemonade"),
                    ("night", "Night"),
                    ("coffee", "Coffee"),
                    ("winter", "Winter"),
                    ("dim", "Dim"),
                    ("nord", "Nord"),
                    ("sunset", "Sunset"),
                    ("caramellatte", "Caramellatte"),
                    ("abyss", "Abyss"),
                    ("silk", "Silk"),
                ],
                default="light",
                max_length=30,
            ),
        ),
    ]
