# Generated by Django 5.2.13 on 2026-05-03 03:20

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_budget_interval_value_user_budget_interval_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="budget_interval",
        ),
        migrations.RemoveField(
            model_name="user",
            name="budget_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="start_pay_date",
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency_value", models.PositiveIntegerField(default=1)),
                (
                    "frequency_unit",
                    models.CharField(
                        choices=[
                            ("days", "Day(s)"),
                            ("weeks", "Week(s)"),
                            ("months", "Month(s)"),
                            ("years", "Year(s)"),
                        ],
                        default="months",
                        max_length=10,
                    ),
                ),
                ("first_pay_date", models.DateField(default=datetime.date(2026, 5, 3))),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Preferences",
            },
        ),
    ]
