# Generated by Django 5.2.13 on 2026-05-03 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_user_budget_interval_remove_user_budget_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="first_pay_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
