# Generated by Django 6.1 on 2026-08-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_userpreferences_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=30,
            ),
        ),
    ]
