# Generated by Django 6.0.5 on 2026-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_userpreferences_first_pay_date"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_category_per_user"
            ),
        ),
    ]
