# Generated by Django 6.0.5 on 2026-05-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_category_unique_category_per_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
