# Generated by Django 6.0.5 on 2026-05-10 07:47

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_category_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_category_per_user",
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                models.F("user"),
                django.db.models.functions.text.Lower("name"),
                name="unique_category_per_user",
            ),
        ),
    ]
