# Generated by Django 6.0.5 on 2026-05-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpreferences",
            old_name="first_pay_date",
            new_name="first_budget_date",
        ),
    ]
