# Generated by Django 6.0.5 on 2026-05-12 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_category_unique_category_per_user_and_more"),
        ("core", "0010_rename_first_pay_date_userpreferences_first_budget_date"),
    ]

    operations = []
