# Generated by Django 6.0.5 on 2026-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_merge_20260512_0104"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="colour",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
