# Generated by Django 6.0.5 on 2026-05-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_category_colour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="colour",
            new_name="color",
        ),
    ]
