# Generated by Django 6.1 on 2026-08-23 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0014_alter_budgetperiod_options"),
        ("transaction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user", "date"], name="tx_user_date_idx"),
        ),
    ]
