# Generated by Django 4.2.25 on 2025-11-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_alter_transaction_credit_alter_transaction_debit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="credit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="debit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
