# Generated by Django 5.2.13 on 2026-05-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_alter_transaction_credit_alter_transaction_debit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="receipt_number",
            new_name="receipt_details",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="credit",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="debit",
        ),
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="processed",
            field=models.BooleanField(default=False),
        ),
    ]
