# Generated by Django 5.2.13 on 2026-05-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transaction",
            "0004_rename_receipt_number_transaction_receipt_details_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="unique_hash",
            field=models.CharField(
                db_index=True, default=12454, max_length=30, unique=True
            ),
            preserve_default=False,
        ),
    ]
