# Generated by Django 5.2.13 on 2026-05-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0005_transaction_unique_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="purchase_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receipt_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="vendor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
