# Generated by Django 5.2.13 on 2026-05-05 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0009_remove_costallocation_user"),
        ("transaction", "0006_alter_transaction_purchase_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="cost_allocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="budget.costallocation",
            ),
        ),
    ]
