# Generated by Django 6.0.5 on 2026-05-09 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0018_incomeallocation_income_and_more"),
        ("transaction", "0007_transaction_cost_allocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="income_allocation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="budget.incomeallocation",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="unique_hash",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
