# Generated by Django 6.0.5 on 2026-07-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_assetbase_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingsaccount",
            name="is_primary",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
