# Generated by Django 6.1 on 2026-08-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_savingsaccount_is_primary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsaccount",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
