# Generated by Django 6.0.5 on 2026-05-13 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency_value", models.PositiveIntegerField(default=1)),
                (
                    "frequency_unit",
                    models.CharField(
                        choices=[
                            ("days", "Day(s)"),
                            ("weeks", "Week(s)"),
                            ("months", "Month(s)"),
                            ("years", "Year(s)"),
                        ],
                        default="months",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                (
                    "keywords",
                    models.CharField(
                        blank=True, help_text="Comma-separated list", max_length=500
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-amount"],
            },
        ),
    ]
