# Generated by Django 6.0.5 on 2026-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
