# Generated by Django 6.0.5 on 2026-07-03 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_income_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prevous_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("new_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_changed", models.DateField()),
                (
                    "income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="income.income"
                    ),
                ),
            ],
            options={
                "ordering": ["date_changed"],
                "abstract": False,
            },
        ),
    ]
