# Generated by Django 6.0.5 on 2026-07-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0003_incomechange"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incomechange",
            old_name="prevous_amount",
            new_name="previous_amount",
        ),
    ]
