# Generated by Django 6.0.5 on 2026-07-07 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0004_rename_prevous_amount_incomechange_previous_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incomechange",
            options={},
        ),
        migrations.AlterField(
            model_name="incomechange",
            name="income",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="income_changes",
                to="income.income",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomechange",
            constraint=models.UniqueConstraint(
                models.F("date_changed"),
                models.F("income"),
                name="unique_income_change_per_day",
            ),
        ),
    ]
