# Generated by Django 6.0.5 on 2026-05-13 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ("budget", "0001_initial"),
        ("core", "0001_initial"),
        ("cost", "0001_initial"),
        ("income", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetperiod",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="costallocation",
            name="budget_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="budget.budgetperiod",
            ),
        ),
        migrations.AddField(
            model_name="costallocation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="costallocation",
            name="cost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cost.cost",
            ),
        ),
        migrations.AddField(
            model_name="incomeallocation",
            name="budget_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="budget.budgetperiod",
            ),
        ),
        migrations.AddField(
            model_name="incomeallocation",
            name="income",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="income.income",
            ),
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("expected_date__isnull", False)),
                fields=("cost", "expected_date"),
                name="unique_cost_per_budget",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomeallocation",
            constraint=models.UniqueConstraint(
                fields=("budget_period", "income", "expected_date"),
                name="unique_income_per_budget",
            ),
        ),
    ]
