# Generated by Django 4.2.25 on 2025-10-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="budget_period",
        ),
        migrations.AddField(
            model_name="budget",
            name="frequency_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budget",
            name="frequency_unit",
            field=models.CharField(
                choices=[
                    ("days", "Days"),
                    ("weeks", "Weeks"),
                    ("months", "Months"),
                    ("years", "Years"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
