# Generated by Django 6.0.5 on 2026-05-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_add_foreign_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costallocation",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="incomeallocation",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
