# Generated by Django 4.2.25 on 2025-11-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_remove_budget_budget_period_budget_frequency_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anchor_date", models.DateField()),
                ("frequency_number", models.IntegerField()),
                (
                    "frequency_unit",
                    models.CharField(
                        choices=[
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                            ("years", "Years"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="budget",
            name="anchor_date",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="frequency_number",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="frequency_unit",
        ),
    ]
