# Generated by Django 6.0.5 on 2026-05-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_alter_costallocation_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costallocation",
            options={"ordering": ["amount"]},
        ),
    ]
