# Generated by Django 4.2.26 on 2025-12-02 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_budgetperiod_remove_budget_anchor_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budget",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
