# Generated by Django 6.0.5 on 2026-06-28 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_bucket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="budgetperiod",
            constraint=models.UniqueConstraint(
                models.F("start_date"),
                models.F("end_date"),
                name="unique_budget_per_period",
            ),
        ),
    ]
