# Generated by Django 5.2.13 on 2026-05-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_rename_anchor_date_budgetperiod_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costallocation",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
