# Generated by Django 6.0.5 on 2026-06-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="costallocation",
            name="note",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
