# Generated by Django 6.0.5 on 2026-06-30 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_budgetperiod_unique_budget_per_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="budgetperiod",
            name="unique_budget_per_period",
        ),
        migrations.AddConstraint(
            model_name="budgetperiod",
            constraint=models.UniqueConstraint(
                models.F("user"),
                models.F("start_date"),
                models.F("end_date"),
                name="unique_budget_per_period",
            ),
        ),
    ]
