# Generated by Django 5.2.13 on 2026-05-03 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_alter_costallocation_paid_amount"),
        ("cost", "0010_rename_frequency_number_cost_frequency_value_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.UniqueConstraint(
                fields=("budget_period", "cost"), name="unique_cost_per_budget"
            ),
        ),
    ]
