# Generated by Django 5.2.13 on 2026-05-03 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0007_costallocation_unique_cost_per_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costallocation",
            name="budget_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="budget.budgetperiod",
            ),
        ),
    ]
