# Generated by Django 5.2.13 on 2026-05-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0008_alter_costallocation_budget_period"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costallocation",
            name="user",
        ),
    ]
