# Generated by Django 6.0.5 on 2026-07-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0008_remove_budgetperiod_unique_budget_per_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="costallocation",
            name="display_expected_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="incomeallocation",
            name="display_expected_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
