# Generated by Django 6.0.5 on 2026-07-07 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0009_costallocation_display_expected_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="costallocation",
            old_name="display_expected_amount",
            new_name="expected_amount",
        ),
        migrations.RenameField(
            model_name="incomeallocation",
            old_name="display_expected_amount",
            new_name="expected_amount",
        ),
        migrations.CreateModel(
            name="RemainderAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="budget.budgetperiod",
                    ),
                ),
            ],
        ),
    ]
