# Generated by Django 5.2.13 on 2026-05-07 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0009_remove_costallocation_user"),
        ("core", "0007_alter_userpreferences_first_pay_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="costallocation",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
    ]
