# Generated by Django 6.0.5 on 2026-05-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0010_costallocation_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costallocation",
            name="paid_amount",
        ),
    ]
