# Generated by Django 6.0.5 on 2026-07-07 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "budget",
            "0010_rename_display_expected_amount_costallocation_expected_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="remainderallocation",
            name="budget_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="remainder",
                to="budget.budgetperiod",
            ),
        ),
    ]
