# Generated by Django 6.0.5 on 2026-07-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0011_alter_remainderallocation_budget_period"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RemainderAllocation",
        ),
    ]
