# Generated by Django 6.0.5 on 2026-05-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0011_remove_costallocation_paid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="costallocation",
            name="expected_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
