# Generated by Django 6.0.7 on 2026-07-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_costallocation_note"),
        ("budget", "0012_delete_remainderallocation"),
    ]

    operations = []
