# Generated by Django 6.0.5 on 2026-05-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0012_costallocation_expected_date"),
        ("core", "0007_alter_userpreferences_first_pay_date"),
        ("cost", "0014_cost_keywords_delete_costkeywords"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="costallocation",
            name="unique_cost_per_budget",
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.UniqueConstraint(
                fields=("budget_period", "cost", "expected_date"),
                name="unique_cost_per_budget",
            ),
        ),
    ]
