# Generated by Django 6.0.5 on 2026-05-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0013_remove_costallocation_unique_cost_per_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costallocation",
            name="cost_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
