# Generated by Django 6.1 on 2026-08-23 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0013_merge_20260730_0604"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgetperiod",
            options={"ordering": ["start_date"]},
        ),
    ]
