# Generated by Django 6.0.5 on 2026-05-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0014_alter_costallocation_cost_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="costallocation",
            old_name="cost_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="costallocation",
            old_name="cost_name",
            new_name="name",
        ),
    ]
