# Generated by Django 6.0.5 on 2026-05-09 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0015_rename_cost_amount_costallocation_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costallocation",
            name="budget_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="budget.budgetperiod",
            ),
        ),
        migrations.CreateModel(
            name="IncomeAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "budget_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="budget.budgetperiod",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
