# Generated by Django 6.0.5 on 2026-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0016_alter_costallocation_budget_period_incomeallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomeallocation",
            name="expected_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
