# Generated by Django 6.0.5 on 2026-05-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0017_incomeallocation_expected_date"),
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incomeallocation",
            name="income",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="income.income",
            ),
        ),
        migrations.AddConstraint(
            model_name="incomeallocation",
            constraint=models.UniqueConstraint(
                fields=("budget_period", "income", "expected_date"),
                name="unique_income_per_budget",
            ),
        ),
    ]
