# Generated by Django 6.0.5 on 2026-05-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0018_incomeallocation_income_and_more"),
        ("core", "0011_merge_20260512_0104"),
        ("cost", "0015_alter_cost_category"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="costallocation",
            name="unique_cost_per_budget",
        ),
        migrations.AddConstraint(
            model_name="costallocation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("expected_date__isnull", False)),
                fields=("cost", "expected_date"),
                name="unique_cost_per_budget",
            ),
        ),
    ]
